/*
 * This source file was generated by the Gradle 'init' task
 */
package com.victortoscano.demo1;

public class App {
    public String getGreeting() {
        return "Hello World! demo1";
    }

    public static void main(String[] args) {
        
        System.out.println(new App().getGreeting());
        System.out.println();
    }
}
